CREATE TABLE BOARD(
SEQ number PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
TITLE VARCHAR2(100) NOT NULL,
CONTENT CLOB NOT NULL,
PASS VARCHAR2(10) NOT NULL,
HIT NUMBER(5) NOT NULL,
REGDATE DATE NOT NULL
REF NUMBER DEFAULT 0;
step NUMBER DEFAULT 0;
DEPTH NUMBER DEFAULT 0;
);
 
CREATE SEQUENCE BOARD_SEQ;
 
CREATE SEQUENCE BOARD_SEQ;
